ALTER TABLE users ADD COLUMN failed_login_attempts INT NOT NULL DEFAULT 0;
ALTER TABLE users ADD COLUMN locked_until TIMESTAMP NULL;

ALTER TABLE financial_records ADD COLUMN version BIGINT NOT NULL DEFAULT 0;
ALTER TABLE financial_records ADD COLUMN idempotency_key VARCHAR(255) UNIQUE NULL;
